### ISSUE TITLE
Composer not working, 

### ISSUE THREAD

**Issue by RetroRipper** [Saleh7/ProxmoxVE_PHP_API#1]
Hello i get this error.

composer require saleh7/proxmoxve_php_api @dev

  [InvalidArgumentException]
  Could not find package saleh7/proxmoxve_php_api.

  Did you mean this?
      saleh7/proxmox-ve_php_api

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by emresaracoglu** [comment]
Hi,

Yes I have same problem.
Can you check composer @Saleh7 ?

**Comment by liuzezhong** [comment]
Yes, I have had this problem too. I can't find the version number.

**Comment by xoxefdp** [comment]
there is a typo on the readme document. 

- Correct package name --> saleh7/proxmox-ve_php_api
- Wrong package name --> saleh7/proxmoxve_php_api
