### ISSUE TITLE
HP Fatal error:  Uncaught Error: Class 'Proxmox\Request' not found

### ISSUE THREAD

**Issue by Fr0ntd00r** [Saleh7/ProxmoxVE_PHP_API#13]
This is the Error:
root@cp:/var/www/html/proxmoxcp# php test.php
PHP Fatal error:  Uncaught Error: Class 'Proxmox\Request' not found in /var/www/html/proxmoxcp/test.php:15
Stack trace:
#0 {main}
  thrown in /var/www/html/proxmoxcp/test.php on line 15

I am using your example script...

**Comment by Fr0ntd00r** [comment]
PHP Version tested on 7.3.3 and 7.4 .. both the same error ... 
my Proxmox login data is correct and its possible to ping it from my webserver ...

**Comment by Saleh7** [comment]
if your php file is a standalone file you have to include vendor/autoload.php yourself
