### ISSUE TITLE
PHP Fatal error:  Class 'Curl\Curl' not found 

### ISSUE THREAD

**Issue by thebringerofdeath789** [Saleh7/ProxmoxVE_PHP_API#7]
Im getting this error: 
PHP Fatal error:  Class 'Curl\Curl' not found in /redacted/proxmox/vendor/saleh7/proxmox-ve_php_api/src/Request.php on line 46

This is on a debian 9 server running php 5.6, with a fresh composer install from the getcomposer site.
php-curl is installed on the system.

**Comment by thebringerofdeath789** [comment]
eventually i tried ' composer require curl/curl' and it resolved the above error but it just gives me quite a few more different errors before failing to get a ticket / etc.


PHP Notice:  Undefined property: Curl\Curl::$data in /proxmox/vendor/saleh7/proxmox-ve_php_api/src/Request.php on line 59
PHP Notice:  Trying to get property of non-object in /proxmox/vendor/saleh7/proxmox-ve_php_api/src/Request.php on line 59
PHP Notice:  Undefined property: Curl\Curl::$data in /proxmox/vendor/saleh7/proxmox-ve_php_api/src/Request.php on line 61
PHP Notice:  Trying to get property of non-object in /proxmox/vendor/saleh7/proxmox-ve_php_api/src/Request.php on line 61

**Comment by ferdl9999** [comment]
Exactly the same problem here. php7.3 installed on debian 9 with a fresh install of composer.

php-curl or php7.3-curl is also installed on the system. I also tried the command **composer require curl/curl** but then there are just other errors.

**Comment by emresaracoglu** [comment]
`composer require php-curl-class/php-curl-class`
